version: "2.1"

services:
  web:
    build: . # build from Dockerfile
    image: nginx-pelican:latest # created image name based on Dockerfile
    stdin_open: true
    tty: true
    restart: always
    ports:
      - "80:80"


